<?php
namespace Kitmage\TrainingEntitlements\Admin;

use Kitmage\TrainingEntitlements\Repository\AuditRepository;
use Kitmage\TrainingEntitlements\Repository\BatchRepository;
use Kitmage\TrainingEntitlements\Repository\RedemptionRepository;
use Kitmage\TrainingEntitlements\Service\TokenService;

final class AdminController {
	private $batches,$redemptions,$audit,$tokens;
	public function __construct(BatchRepository $b,RedemptionRepository $r,AuditRepository $a,TokenService $t){$this->batches=$b;$this->redemptions=$r;$this->audit=$a;$this->tokens=$t;}
	public function register(){add_action('admin_menu',array($this,'menu'));add_action('admin_post_kte_batch_action',array($this,'action'));}
	public function menu(){add_submenu_page('woocommerce',__('Training Entitlements','kitmage-training-entitlements'),__('Training Entitlements','kitmage-training-entitlements'),'manage_woocommerce','kte-batches',array($this,'screen'));}
	public function screen(){if(!current_user_can('manage_woocommerce'))wp_die(esc_html__('Access denied.','kitmage-training-entitlements'));$id=absint($_GET['batch_id']??0);echo '<div class="wrap"><h1>'.esc_html__('Training Entitlements','kitmage-training-entitlements').'</h1>';if($id)$this->detail($id);else $this->listing();echo '</div>';}
	private function listing(){$page=max(1,absint($_GET['paged']??1));$limit=25;$total=0;$rows=$this->batches->query(array('status'=>sanitize_key($_GET['status']??''),'s'=>sanitize_text_field($_GET['s']??''),'limit'=>$limit,'offset'=>($page-1)*$limit),$total);echo '<form><input type="hidden" name="page" value="kte-batches"><p class="search-box"><input name="s" value="'.esc_attr($_GET['s']??'').'"><button class="button">'.esc_html__('Search','kitmage-training-entitlements').'</button></p></form><table class="widefat striped"><thead><tr><th>ID</th><th>'.esc_html__('Purchaser','kitmage-training-entitlements').'</th><th>'.esc_html__('Course','kitmage-training-entitlements').'</th><th>'.esc_html__('Order / Subscription','kitmage-training-entitlements').'</th><th>'.esc_html__('Seats','kitmage-training-entitlements').'</th><th>'.esc_html__('Expiration','kitmage-training-entitlements').'</th><th>'.esc_html__('Status','kitmage-training-entitlements').'</th></tr></thead><tbody>';foreach($rows as $r){$u=get_userdata($r->customer_user_id);printf('<tr><td><a href="%s">%d</a></td><td>%s</td><td>%s</td><td>#%d / %s</td><td>%d / %d (%d reserved)</td><td>%s</td><td>%s</td></tr>',esc_url(admin_url('admin.php?page=kte-batches&batch_id='.$r->id)),$r->id,esc_html($u?$u->user_email:'#'.$r->customer_user_id),esc_html(get_the_title($r->course_id)?:'#'.$r->course_id),$r->order_id,$r->subscription_id?'#'.$r->subscription_id:'—',$r->entitlements_used,$r->entitlements_total,$r->entitlements_reserved,esc_html($r->expires_at),esc_html($r->status));}echo '</tbody></table>';echo wp_kses_post(paginate_links(array('base'=>add_query_arg('paged','%#%'),'total'=>ceil($total/$limit),'current'=>$page)));}
	private function detail($id){$b=$this->batches->get($id);if(!$b){echo '<p>'.esc_html__('Batch not found.','kitmage-training-entitlements').'</p>';return;}$u=get_userdata($b->customer_user_id);echo '<h2>'.esc_html(sprintf(__('Batch #%d','kitmage-training-entitlements'),$id)).'</h2><dl>';foreach(array('Purchaser'=>$u?$u->user_email:'#'.$b->customer_user_id,'Course'=>(get_the_title($b->course_id)?:'#'.$b->course_id),'Order'=>$b->order_id,'Order item'=>$b->order_item_id,'Subscription'=>$b->subscription_id,'Product'=>$b->product_id,'Variation'=>$b->variation_id,'Total'=>$b->entitlements_total,'Used'=>$b->entitlements_used,'Reserved'=>$b->entitlements_reserved,'Created'=>$b->created_at,'Expires'=>$b->expires_at,'Status'=>$b->status) as $k=>$v)echo '<dt><strong>'.esc_html($k).'</strong></dt><dd>'.esc_html($v).'</dd>';echo '</dl><h3>'.esc_html__('Actions','kitmage-training-entitlements').'</h3><form action="'.esc_url(admin_url('admin-post.php')).'" method="post"><input type="hidden" name="action" value="kte_batch_action"><input type="hidden" name="batch_id" value="'.$id.'">';wp_nonce_field('kte_batch_'.$id);echo '<select name="operation"><option value="revoke">Revoke</option><option value="reactivate">Reactivate</option><option value="regenerate">Regenerate token</option><option value="expiration">Change expiration</option><option value="total">Change total</option></select> <input name="value" placeholder="Value"><button class="button">Apply</button></form><h3>'.esc_html__('Redemptions','kitmage-training-entitlements').'</h3><table class="widefat"><tr><th>User</th><th>Name</th><th>Email</th><th>Status</th><th>Redeemed</th></tr>';foreach($this->redemptions->for_batch($id) as $r)printf('<tr><td>%d</td><td>%s</td><td>%s</td><td>%s</td><td>%s</td></tr>',$r->user_id,esc_html(trim($r->first_name_snapshot.' '.$r->last_name_snapshot)),esc_html($r->email_snapshot),esc_html($r->status),esc_html($r->redeemed_at));echo '</table><h3>'.esc_html__('Audit log','kitmage-training-entitlements').'</h3><ul>';foreach($this->audit->for_batch($id) as $a)echo '<li>'.esc_html($a->created_at.' — '.$a->action).'</li>';echo '</ul>';}
	public function action(){if(!current_user_can('manage_woocommerce'))wp_die('Access denied');$id=absint($_POST['batch_id']??0);check_admin_referer('kte_batch_'.$id);$b=$this->batches->get($id);if(!$b)wp_die('Invalid batch');$op=sanitize_key($_POST['operation']??'');$old=(array)$b;$new=array();if('revoke'===$op){$new['status']='revoked';do_action('kitmage_training_entitlements/batch_revoked',$id,get_current_user_id());}elseif('reactivate'===$op&&'revoked'===$b->status&&$b->expires_at>current_time('mysql',true)&&$b->entitlements_used+$b->entitlements_reserved<$b->entitlements_total){$new['status']='active';}elseif('expiration'===$op){$time=strtotime(sanitize_text_field($_POST['value']??''));if($time)$new['expires_at']=gmdate('Y-m-d H:i:s',$time);}elseif('total'===$op){$total=absint($_POST['value']??0);if($total>=$b->entitlements_used+$b->entitlements_reserved)$new['entitlements_total']=$total;}elseif('regenerate'===$op){$raw=$this->tokens->generate();$new=array('token_hash'=>$this->tokens->hash($raw),'encrypted_token'=>$this->tokens->encrypt($raw),'token_version'=>$b->token_version+1);}if($new){$this->batches->update($id,$new);$this->audit->add($id,$op,$old,$new);}wp_safe_redirect(admin_url('admin.php?page=kte-batches&batch_id='.$id));exit;}
}
