<?php
namespace Kitmage\TrainingEntitlements\WooCommerce;

use Kitmage\TrainingEntitlements\Repository\AuditRepository;
use Kitmage\TrainingEntitlements\Repository\BatchRepository;
use Kitmage\TrainingEntitlements\Service\TokenService;
use Kitmage\TrainingEntitlements\Tutor\Compatibility;

final class Integration {
	private $batches,$audit,$tokens;
	public function __construct(BatchRepository $b,AuditRepository $a,TokenService $t){$this->batches=$b;$this->audit=$a;$this->tokens=$t;}
	public function register(){
		add_action('woocommerce_product_options_general_product_data',array($this,'fields'));add_action('woocommerce_process_product_meta',array($this,'save_product'));
		add_action('woocommerce_variation_options',array($this,'variation_fields'),10,3);add_action('woocommerce_save_product_variation',array($this,'save_variation'),10,2);
		add_action('woocommerce_payment_complete',array($this,'provision'));add_action('woocommerce_order_status_processing',array($this,'provision'));add_action('woocommerce_order_status_completed',array($this,'provision'));
		add_action('woocommerce_subscription_renewal_payment_complete',array($this,'renewal'),10,2);add_action('woocommerce_order_fully_refunded',array($this,'refund'),10,2);
		add_action('init',array($this,'endpoint'));add_filter('woocommerce_account_menu_items',array($this,'menu'));add_action('woocommerce_account_training-enrollments_endpoint',array($this,'account'));
		add_action('wp_enqueue_scripts',array($this,'assets'));
		add_filter('woocommerce_login_redirect',array($this,'auth_redirect'),10,2);add_filter('woocommerce_registration_redirect',array($this,'registration_redirect'));
	}
	private function course_options(){ $options=array(''=>__('Select an entitlement-only course','kitmage-training-entitlements'));if(!Compatibility::supported())return $options;$q=get_posts(array('post_type'=>'courses','posts_per_page'=>-1,'post_status'=>'publish'));foreach($q as $p)if(Compatibility::eligible($p->ID))$options[$p->ID]=$p->post_title;return $options; }
	public function fields(){echo '<div class="options_group">';woocommerce_wp_checkbox(array('id'=>'_kte_enabled','label'=>__('Enable Training Entitlements','kitmage-training-entitlements')));woocommerce_wp_select(array('id'=>'_kte_course_id','label'=>__('Tutor LMS Course','kitmage-training-entitlements'),'options'=>$this->course_options(),'description'=>__('Only courses using Pricing Model → Entitlement Only are accepted.','kitmage-training-entitlements')));woocommerce_wp_text_input(array('id'=>'_kte_seats','label'=>__('Entitlements Per Unit','kitmage-training-entitlements'),'type'=>'number','custom_attributes'=>array('min'=>1,'step'=>1)));woocommerce_wp_text_input(array('id'=>'_kte_days','label'=>__('Redemption Window','kitmage-training-entitlements'),'type'=>'number','value'=>get_post_meta(get_the_ID(),'_kte_days',true)?:30,'custom_attributes'=>array('min'=>1,'step'=>1)));echo '</div>';}
	public function save_product($id){$enabled=isset($_POST['_kte_enabled'])?'yes':'no';$course=absint($_POST['_kte_course_id']??0);if('yes'===$enabled&&!Compatibility::eligible($course)){$enabled='no';\WC_Admin_Meta_Boxes::add_error(__('Training Entitlements was disabled because the selected course is not Entitlement Only.','kitmage-training-entitlements'));}update_post_meta($id,'_kte_enabled',$enabled);update_post_meta($id,'_kte_course_id',$course);update_post_meta($id,'_kte_seats',max(1,absint($_POST['_kte_seats']??1)));update_post_meta($id,'_kte_days',max(1,absint($_POST['_kte_days']??30)));}
	public function variation_fields($loop,$data,$variation){woocommerce_wp_select(array('id'=>"_kte_course_id[$loop]",'name'=>"_kte_course_id[$loop]",'value'=>get_post_meta($variation->ID,'_kte_course_id',true),'label'=>__('Entitlement course override','kitmage-training-entitlements'),'options'=>$this->course_options()));woocommerce_wp_text_input(array('id'=>"_kte_seats[$loop]",'name'=>"_kte_seats[$loop]",'value'=>get_post_meta($variation->ID,'_kte_seats',true),'label'=>__('Seat override','kitmage-training-entitlements'),'type'=>'number'));woocommerce_wp_text_input(array('id'=>"_kte_days[$loop]",'name'=>"_kte_days[$loop]",'value'=>get_post_meta($variation->ID,'_kte_days',true),'label'=>__('Window override','kitmage-training-entitlements'),'type'=>'number'));}
	public function save_variation($id,$loop){foreach(array('_kte_course_id','_kte_seats','_kte_days') as $key){$v=isset($_POST[$key][$loop])?absint($_POST[$key][$loop]):0;$v?update_post_meta($id,$key,$v):delete_post_meta($id,$key);}}
	private function config($product,$variation){$parent=$variation?$product->get_parent_id():$product->get_id();if('yes'!==get_post_meta($parent,'_kte_enabled',true))return null;$vid=$variation?$product->get_id():0;$get=static function($key,$vid,$parent){$v=$vid?get_post_meta($vid,$key,true):'';return ''!==$v?$v:get_post_meta($parent,$key,true);};$course=absint($get('_kte_course_id',$vid,$parent));if(!Compatibility::eligible($course))return null;return array('course'=>$course,'seats'=>max(1,absint($get('_kte_seats',$vid,$parent))),'days'=>max(1,absint($get('_kte_days',$vid,$parent))));}
	public function provision($order_id){$order=wc_get_order($order_id);if(!$order||!$order->is_paid())return;$subscription=absint($order->get_meta('_subscription_renewal'));if(!$subscription&&function_exists('wcs_get_subscriptions_for_order')){$linked=wcs_get_subscriptions_for_order($order_id,array('order_type'=>'parent'));if($linked){$first=reset($linked);$subscription=(int)$first->get_id();}}foreach($order->get_items('line_item') as $item_id=>$item){if($this->batches->by_order_item($item_id))continue;$product=$item->get_product();if(!$product)continue;$variation=$product->is_type('variation');$c=$this->config($product,$variation);if(!$c)continue;$total=$c['seats']*max(1,(int)$item->get_quantity());$token=$this->tokens->generate();$created=$order->get_date_paid()?:$order->get_date_created();$created_utc=$created->setTimezone(new \DateTimeZone('UTC'));$expires=(clone $created_utc)->modify('+'.$c['days'].' days');$data=array('token_hash'=>$this->tokens->hash($token),'encrypted_token'=>$this->tokens->encrypt($token),'customer_user_id'=>(int)$order->get_customer_id(),'order_id'=>(int)$order_id,'order_item_id'=>(int)$item_id,'subscription_id'=>$subscription,'product_id'=>(int)$item->get_product_id(),'variation_id'=>(int)$item->get_variation_id(),'course_id'=>$c['course'],'entitlements_total'=>$total,'created_at'=>$created_utc->format('Y-m-d H:i:s'),'expires_at'=>$expires->format('Y-m-d H:i:s'),'status'=>'active','created_by'=>$subscription?'subscription_renewal':'woocommerce','updated_at'=>current_time('mysql',true));$id=$this->batches->create($data);if($id){$item->add_meta_data('_kte_tutor_course_id',$c['course'],true);$item->add_meta_data('_kte_entitlements_per_unit',$c['seats'],true);$item->add_meta_data('_kte_total_entitlements',$total,true);$item->add_meta_data('_kte_redemption_window',$c['days'],true);$item->save();$this->audit->add($id,'batch_created',null,array('total'=>$total));do_action('kitmage_training_entitlements/batch_created',$id,(int)$order_id,(int)$item_id);}}}
	public function renewal($subscription,$order){if(is_object($order))$this->provision($order->get_id());}
	public function refund($order_id){global $wpdb;$ids=$wpdb->get_col($wpdb->prepare("SELECT id FROM {$wpdb->prefix}kte_batches WHERE order_id=%d AND status!='refunded'",$order_id));$this->batches->refund_order($order_id);foreach($ids as $id)$this->audit->add($id,'full_refund_disablement',null,'refunded');}
	public function endpoint(){add_rewrite_endpoint('training-enrollments',EP_ROOT|EP_PAGES);}
	public function menu($items){$logout=$items['customer-logout']??null;unset($items['customer-logout']);$items['training-enrollments']=__('Training Enrollments','kitmage-training-entitlements');if($logout)$items['customer-logout']=$logout;return $items;}
	public function account(){if(!is_user_logged_in())return;$batches=$this->batches->for_customer(get_current_user_id());$tokens=$this->tokens;include KTE_PATH.'templates/my-account/batches.php';}
	public function assets(){if(function_exists('is_account_page')&&is_account_page())wp_enqueue_script('kte-account',plugins_url('assets/js/account.js',KTE_FILE),array(),KTE_VERSION,true);}
	public function auth_redirect($redirect){return !empty($_REQUEST['redirect_to'])?wp_validate_redirect(wp_unslash($_REQUEST['redirect_to']),$redirect):$redirect;}
	public function registration_redirect($redirect){return $this->auth_redirect($redirect);}
}
