<?php defined('ABSPATH')||exit; get_header();
$messages=array('invalid'=>__('This invitation is invalid.','kitmage-training-entitlements'),'expired'=>__('This invitation has expired.','kitmage-training-entitlements'),'revoked'=>__('This invitation has been revoked.','kitmage-training-entitlements'),'refunded'=>__('This invitation is no longer available.','kitmage-training-entitlements'),'exhausted'=>__('All enrollments from this invitation have been used.','kitmage-training-entitlements'),'already_redeemed'=>__('You already used this invitation and are enrolled in this course.','kitmage-training-entitlements'),'already_enrolled'=>__('You are already enrolled in this course. No entitlement was used.','kitmage-training-entitlements'),'course_unavailable'=>__('This course is currently unavailable.','kitmage-training-entitlements'),'unavailable'=>__('No enrollment places are currently available.','kitmage-training-entitlements'),'reservation_failed'=>__('Enrollment could not be reserved. Please try again.','kitmage-training-entitlements'),'enrollment_failed'=>__('We could not complete your enrollment. No seat was consumed; please try again.','kitmage-training-entitlements'));
?>
<main class="kte-redemption woocommerce"><section class="woocommerce-info"><h1><?php echo esc_html($course?$course->post_title:__('Training invitation','kitmage-training-entitlements')); ?></h1>
<?php if('login_required'===$state): ?><p><?php esc_html_e('Sign in or create an account to use this invitation.','kitmage-training-entitlements'); ?></p><a class="button" href="<?php echo esc_url(add_query_arg('redirect_to',home_url('/training/redeem/'.rawurlencode($token).'/'),wc_get_page_permalink('myaccount'))); ?>"><?php esc_html_e('Sign in or register','kitmage-training-entitlements'); ?></a>
<?php elseif('ready'===$state): ?><p><?php printf(esc_html__('Invitation expires %s.','kitmage-training-entitlements'),esc_html(wp_date(get_option('date_format').' '.get_option('time_format'),strtotime($batch->expires_at.' UTC')))); ?></p><form method="post"><?php wp_nonce_field('kte_redeem_'.$batch->id); ?><button class="button alt" type="submit"><?php esc_html_e('Enroll now','kitmage-training-entitlements'); ?></button></form>
<?php elseif('success'===$state): ?><h2><?php esc_html_e("You're enrolled.",'kitmage-training-entitlements'); ?></h2><p><?php esc_html_e('Your enrollment is now active.','kitmage-training-entitlements'); ?></p><a class="button alt" href="<?php echo esc_url(get_permalink($batch->course_id)); ?>"><?php esc_html_e('Go to Course','kitmage-training-entitlements'); ?></a>
<?php else: ?><p><?php echo esc_html($messages[$state]??__('This invitation is unavailable.','kitmage-training-entitlements')); ?></p><?php if(in_array($state,array('already_redeemed','already_enrolled'),true)): ?><a class="button" href="<?php echo esc_url(get_permalink($batch->course_id)); ?>"><?php esc_html_e('Go to Course','kitmage-training-entitlements'); ?></a><?php endif; endif; ?></section></main>
<?php get_footer();
